/*

*/
package org.blr.error;

public enum ErrorCode {
    REPOSITORY_NOT_FOUND,
    INVALID_COMMIT,
    COMMIT_NOT_ON_MAIN,
    GRAPH_BUILD_ALREADY_RUNNING,
    NODE_PROCESS_START_FAILED,
    CODEGRAPH_EXECUTION_FAILED,
    CODEGRAPH_TIMEOUT,
    GRAPH_VALIDATION_FAILED,
    GRAPH_ARTIFACT_PACKAGING_FAILED,
    GRAPH_ARTIFACT_UPLOAD_FAILED,
    GRAPH_PUBLICATION_FAILED,
    INVALID_REQUEST,
    INTERNAL_ERROR
}
